### PR TITLE
another makefile update

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by sphaero** [comment]
What platform are you on? It seems you haven't changed a lot in the makefile but the diff shows all lines have changed. It's quite difficult to see changes then. I expect different line endings? Could you try to recommit with different line endings?
This is what file says about the current Makefile:

```
$ file Makefile 
Makefile: makefile script, ASCII text, with very long lines, with CRLF line terminators
```

What does yours say?

**Comment by ghost** [comment]
hi sphaero

i'm on rpi/raspbian using vim.
i don't think it has to do with line endings
because "file Makefile" shows no such issue here.

"$ file Makefile
Makefile: makefile script, ASCII text"

mainly i did the following changes:
- reordered a lot of lines to make it more readable
- removed unused logic like the fame stuff selection
- removed armv7 and neon stuff, rpi is armv6
- axed double enabled optimization flags
- used -O2 instead of -O3 as it swaps a lot when building on rpi
- used sound_sdl_new for proper sound

**Comment by sphaero** [comment]
Then strange that I can't merge this pr. Is your repo in sync with this one? Can you do a git pull of master of this repo?

**Comment by ghost** [comment]
ah ok! my fork was not in sync, please try again.

**Pull request merged**
